name: Bug
description: Report a defect or regression.
title: "fix: "
labels: ["type:bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is broken and how to reproduce?
      placeholder: Steps to reproduce.
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What does "fixed" look like?
      placeholder: "- [ ] ..."
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - area:viewer
        - area:assets
        - area:backend
        - area:tools
        - area:ci
        - area:docs
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - prio:p0
        - prio:p1
        - prio:p2
    validations:
      required: true
