name: Task
description: General task or chore.
title: "chore: "
labels: ["type:chore"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Definition of done for this task.
      placeholder: "- [ ] ..."
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - area:viewer
        - area:assets
        - area:backend
        - area:tools
        - area:ci
        - area:docs
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - prio:p0
        - prio:p1
        - prio:p2
    validations:
      required: true
